server:
    port: 8080
    context-path: /
spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/boot-security?characterEncoding=utf8
        username: root
#        password: 123456
        password: root

    jpa:
        hibernate:
#          create:每次运行该程序，没有表格会新建表格，表内有数据会清空
          update:每次运行程序，没有表格会新建表格，表内有数据不会清空，只会更新
#         none:不做任何操作
#          ddl-auto: none
        show-sql: true
    mvc:
        view:
            prefix: /WEB-INF/
            suffix: .jsp
imooc:
    security:
        browser:
#            loginPage: /demo-signIn.html
            loginType: REDIRECT

